
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.prefix }}-camunda-pod
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.prefix }}-camunda-pod
    spec:
      containers:
        - name: {{ .Values.deployment.camundapod.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.camundapod.image }}
          ports:
            - name: http-port
              containerPort: 8080